spring.application.name=he-thong-quan-ly-thuoc-ctut

spring.datasource.url=jdbc:mysql://localhost:3306/he_thong_quan_ly_thuoc_ctut
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

#khái báo driver jdbc mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Hibernate sẽ tự động cập nhật cấu trúc bảng trong database theo entity Java (nếu có thay đổi).
spring.jpa.hibernate.ddl-auto=update

#JPA/HIBERNATE LOGGING

#format lại câu SQL cho dễ đọc, nếu không có thì SQL in ra 1 dòng dài, có thì xuống dòng đẹp
spring.jpa.properties.hibernate.format_sql=true

#LoGGING
logging.level.root=WARN
logging.level.org.springframework.security=WARN
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=WARN
logging.level.student.ctuet.edu.vn.hethongquanlythuoc=DEBUG

#JWT CONFIG
jwt.secret=${JWT_SECRET}
jwt.access-expiration=900000
# 900000ms = 15 phút 

jwt.refresh-expiration=604800000
# 604800000ms = 7 ngày 

#REDIS CONFIG
spring.data.redis.host=localhost
spring.data.redis.port=6379

#SWAGGER CONFIG
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
spring.mvc.pathmatch.use-suffix-pattern=false
springdoc.swagger-ui.disable-swagger-default-url=true

