spring.application.name=he-thong-quan-ly-thuoc-ctut

# ===== DATABASE (MySQL - Aiven) =====
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=30000

# Hibernate tự động cập nhật cấu trúc bảng theo entity Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# ===== LOGGING =====
logging.level.root=WARN
logging.level.org.springframework.security=WARN
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=WARN
logging.level.student.ctuet.edu.vn.hethongquanlythuoc=DEBUG

# ===== JWT CONFIG =====
jwt.secret=${JWT_SECRET}
jwt.access-expiration=900000
# 900000ms = 15 phút

jwt.refresh-expiration=604800000
# 604800000ms = 7 ngày

# ===== REDIS CONFIG (Upstash) =====
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=true

# ===== SWAGGER CONFIG =====
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
spring.mvc.pathmatch.use-suffix-pattern=false
springdoc.swagger-ui.disable-swagger-default-url=true

# ===== SERVER =====
server.port=${PORT:8080}